In [1]:
import numpy as np
from numpy.linalg import inv

In [ ]:
#matriz de restricciones
A = np.array([[15, -36, 30, -54, 39, -92, 54, -76, 75, 30, 54, -36, -18, 79, 0, 0, 0, 0, 0, 0], 
     [-41, -38, 90, 74, 56, 37, 32, 92, 32, 35, 57, 64, 98, -51, 0, 0, 0, 0, 0, 0], 
     [-48, 38, -18, 20, 89, 15, 56, -64, -78, 35, 65, 55, -87, -23, 0, 0, 0, 0, 0, 0],
     [-65, 36, 77, 49, 74, 68, 56, -91, 37, 78, 9, 63, -36, -63, 0, 0, 0, 0, 0, 0],
     [100, 93, 50, 86, 50, 81, 67, 52, 52, 87, 61, 72, 68, 97, 1, 0, 0, 0, 0, 0],
     [-23, -27, -69, 40, -93, 48, -11, -51, 64, -82, 0, 47, 65, 97, 0, 1, 0, 0, 0, 0],
     [90, 18, 51, -78, 2, 98, -11, 74, -1, -7, 45, 70, 88, 1, 0, 0, 1, 0, 0, 0],
     [-3, 95, -57, -18, -33, 100, -18, 85, 84, -17, 42, 29, -52, 74, 0, 0, 0, 1, 0, 0],
     [47, 24, -19, 89, -74, 77, 13, 60, 83, 66, -17, -24, -3, 58, 0, 0, 0, 0, 1, 0],
     [-75, 43, 46, 72, 21, -99, 97, 92, 82, -25, 41, 50, -5, 57, 0, 0, 0, 0, 0, 1]])

#coeficientes de la función objetivo
c = np.array([44,18,60,27,-79,-51,92,-78,-69,-35,26,-56,-10,-55,0,0,0,0,0,0])

#términos independientes de las restricciones
b = np.array([64, 537, 55, 292, 1017, 6, 441, 312, 381, 398])


In [ ]:
# formato fase 1
c_2 = c
a=A
m=len(A)
n=len(A[0])
num_variables_no_basicas = n-m
num_variables_basicas = m
id=np.identity(m) #matriz identidad para las variables artificiales
ones=np.ones(m) #función objetivo de la fase I
c_prefase_1=np.zeros(n) 
A_fase_1 = np.insert(a,n,id,axis=1)
c_fase_1 = np.insert(c_prefase_1,n,ones,axis=0)
indices_basicas = np.array(range(n,n+m))
indices_no_basicas = np.array(range(n))
indices_inventadas = np.array(range(n,n+m))

In [213]:
c_fase_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
filas=np.array(range(m))
filas
B = A_fase_1[np.ix_(filas,indices_basicas)]
An = A_fase_1[np.ix_(filas,indices_no_basicas)]
print(An)
print(B)



[[ 15 -36  30 -54  39 -92  54 -76  75  30  54 -36 -18  79   0   0   0   0
    0   0]
 [-41 -38  90  74  56  37  32  92  32  35  57  64  98 -51   0   0   0   0
    0   0]
 [-48  38 -18  20  89  15  56 -64 -78  35  65  55 -87 -23   0   0   0   0
    0   0]
 [-65  36  77  49  74  68  56 -91  37  78   9  63 -36 -63   0   0   0   0
    0   0]
 [100  93  50  86  50  81  67  52  52  87  61  72  68  97   1   0   0   0
    0   0]
 [-23 -27 -69  40 -93  48 -11 -51  64 -82   0  47  65  97   0   1   0   0
    0   0]
 [ 90  18  51 -78   2  98 -11  74  -1  -7  45  70  88   1   0   0   1   0
    0   0]
 [ -3  95 -57 -18 -33 100 -18  85  84 -17  42  29 -52  74   0   0   0   1
    0   0]
 [ 47  24 -19  89 -74  77  13  60  83  66 -17 -24  -3  58   0   0   0   0
    1   0]
 [-75  43  46  72  21 -99  97  92  82 -25  41  50  -5  57   0   0   0   0
    0   1]]
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0

In [ ]:
cn = c_fase_1[indices_no_basicas]
cb = c_fase_1[indices_basicas]
B_inv = inv(B)

Xb=np.matmul(B_inv,b)

z=np.dot(cb,Xb)

#check if all xb is positive
if all(val>0 for val in Xb):
    #good
    print('Good')


Good


In [216]:
print(cn,cb,Xb,z,b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [  64.  537.   55.  292. 1017.    6.  441.  312.  381.  398.] 3503.0 [  64  537   55  292 1017    6  441  312  381  398]


In [ ]:
cb_x_invB=np.matmul(cb,B_inv)
cb_x_invB_An=np.matmul(cb_x_invB,An)
r=cn-cb_x_invB_An

print(r)
#select first negative variable following bland rule
#indice_en_r_variable_entrada
if all(val>0 for val in r):
    print('SBF es óptima')
    #stop
else:
    q=0
    for i in range(len(r)):
        if r[i]<0:
            q=i
            break
    
q

[   3. -246. -181. -280. -131. -333. -335. -173. -430. -200. -357. -390.
 -118. -326.   -1.   -1.   -1.   -1.   -1.   -1.]


1

In [218]:
r

array([   3., -246., -181., -280., -131., -333., -335., -173., -430.,
       -200., -357., -390., -118., -326.,   -1.,   -1.,   -1.,   -1.,
         -1.,   -1.])

In [219]:
An

array([[ 15, -36,  30, -54,  39, -92,  54, -76,  75,  30,  54, -36, -18,
         79,   0,   0,   0,   0,   0,   0],
       [-41, -38,  90,  74,  56,  37,  32,  92,  32,  35,  57,  64,  98,
        -51,   0,   0,   0,   0,   0,   0],
       [-48,  38, -18,  20,  89,  15,  56, -64, -78,  35,  65,  55, -87,
        -23,   0,   0,   0,   0,   0,   0],
       [-65,  36,  77,  49,  74,  68,  56, -91,  37,  78,   9,  63, -36,
        -63,   0,   0,   0,   0,   0,   0],
       [100,  93,  50,  86,  50,  81,  67,  52,  52,  87,  61,  72,  68,
         97,   1,   0,   0,   0,   0,   0],
       [-23, -27, -69,  40, -93,  48, -11, -51,  64, -82,   0,  47,  65,
         97,   0,   1,   0,   0,   0,   0],
       [ 90,  18,  51, -78,   2,  98, -11,  74,  -1,  -7,  45,  70,  88,
          1,   0,   0,   1,   0,   0,   0],
       [ -3,  95, -57, -18, -33, 100, -18,  85,  84, -17,  42,  29, -52,
         74,   0,   0,   0,   1,   0,   0],
       [ 47,  24, -19,  89, -74,  77,  13,  60,  83,  66, -17, -

In [220]:
B

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [221]:
q


1

In [ ]:
q=np.array([q])
Aq = A_fase_1[np.ix_(filas,q)]
q_int=int(q)

C:\Users\mikel\AppData\Local\Temp\ipykernel_23524\1304036990.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  q_int=int(q)


In [223]:
q_int

1

In [224]:
Aq

array([[-36],
       [-38],
       [ 38],
       [ 36],
       [ 93],
       [-27],
       [ 18],
       [ 95],
       [ 24],
       [ 43]])

In [ ]:
db=np.matmul(-B_inv,Aq)
db_min=np.matmul(-B_inv,Aq)
for i in range(m):
    if db_min[i]>0:
        db_min[i]=-0.0001

if all(val>=0 for val in db):
    print('(PL) no acotado')
    #stop

In [226]:
db

array([[ 36.],
       [ 38.],
       [-38.],
       [-36.],
       [-93.],
       [ 27.],
       [-18.],
       [-95.],
       [-24.],
       [-43.]])

In [227]:
db_min

array([[ -0.0001],
       [ -0.0001],
       [-38.    ],
       [-36.    ],
       [-93.    ],
       [ -0.0001],
       [-18.    ],
       [-95.    ],
       [-24.    ],
       [-43.    ]])

In [228]:
Xb

array([  64.,  537.,   55.,  292., 1017.,    6.,  441.,  312.,  381.,
        398.])

In [229]:
pretheta=np.empty(0)
for i in range(m):
    print(-Xb[i]/db_min[i])
    pretheta=np.insert(pretheta,i,-Xb[i]/db_min[i])

theta=np.min(pretheta)
theta_index=np.argmin(pretheta)
pretheta

[640000.]
[5370000.]
[1.44736842]
[8.11111111]
[10.93548387]
[60000.]
[24.5]
[3.28421053]
[15.875]
[9.25581395]


array([ 640000.        , 5370000.        ,       1.44736842,
             8.11111111,      10.93548387,   60000.        ,
            24.5       ,       3.28421053,      15.875     ,
             9.25581395])

In [230]:
theta_index

np.int64(2)

In [231]:
theta

np.float64(1.4473684210526316)

In [232]:

theta_num=float(theta)
theta_index_int=int(theta_index)
theta_num


1.4473684210526316

In [233]:
theta_index_int

2

In [234]:
p=theta_index_int
p

2

In [235]:
theta_num

1.4473684210526316

In [236]:
db

array([[ 36.],
       [ 38.],
       [-38.],
       [-36.],
       [-93.],
       [ 27.],
       [-18.],
       [-95.],
       [-24.],
       [-43.]])

In [237]:
theta_x_db= theta_num*db
print(theta_num)
print(db)
print(theta_x_db)

1.4473684210526316
[[ 36.]
 [ 38.]
 [-38.]
 [-36.]
 [-93.]
 [ 27.]
 [-18.]
 [-95.]
 [-24.]
 [-43.]]
[[  52.10526316]
 [  55.        ]
 [ -55.        ]
 [ -52.10526316]
 [-134.60526316]
 [  39.07894737]
 [ -26.05263158]
 [-137.5       ]
 [ -34.73684211]
 [ -62.23684211]]


In [238]:
Xb

array([  64.,  537.,   55.,  292., 1017.,    6.,  441.,  312.,  381.,
        398.])

In [239]:
Xb_actual=np.zeros(m)
theta_x_db

array([[  52.10526316],
       [  55.        ],
       [ -55.        ],
       [ -52.10526316],
       [-134.60526316],
       [  39.07894737],
       [ -26.05263158],
       [-137.5       ],
       [ -34.73684211],
       [ -62.23684211]])

In [240]:
for i in range(m):
    #print(i)
    Xb_actual[i]=Xb[i]+theta_x_db[i]
    if Xb_actual[i]==0:
        Xb_actual[i]=theta_num

Xb_actual

C:\Users\mikel\AppData\Local\Temp\ipykernel_23524\168470611.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Xb_actual[i]=Xb[i]+theta_x_db[i]


array([116.10526316, 592.        ,   1.44736842, 239.89473684,
       882.39473684,  45.07894737, 414.94736842, 174.5       ,
       346.26315789, 335.76315789])

In [241]:
np.set_printoptions(suppress=True)
print(Xb_actual)

[116.10526316 592.           1.44736842 239.89473684 882.39473684
  45.07894737 414.94736842 174.5        346.26315789 335.76315789]


In [242]:
q

array([1])

In [243]:
p

2

In [244]:
Xb_actual

array([116.10526316, 592.        ,   1.44736842, 239.89473684,
       882.39473684,  45.07894737, 414.94736842, 174.5       ,
       346.26315789, 335.76315789])

In [245]:
An

array([[ 15, -36,  30, -54,  39, -92,  54, -76,  75,  30,  54, -36, -18,
         79,   0,   0,   0,   0,   0,   0],
       [-41, -38,  90,  74,  56,  37,  32,  92,  32,  35,  57,  64,  98,
        -51,   0,   0,   0,   0,   0,   0],
       [-48,  38, -18,  20,  89,  15,  56, -64, -78,  35,  65,  55, -87,
        -23,   0,   0,   0,   0,   0,   0],
       [-65,  36,  77,  49,  74,  68,  56, -91,  37,  78,   9,  63, -36,
        -63,   0,   0,   0,   0,   0,   0],
       [100,  93,  50,  86,  50,  81,  67,  52,  52,  87,  61,  72,  68,
         97,   1,   0,   0,   0,   0,   0],
       [-23, -27, -69,  40, -93,  48, -11, -51,  64, -82,   0,  47,  65,
         97,   0,   1,   0,   0,   0,   0],
       [ 90,  18,  51, -78,   2,  98, -11,  74,  -1,  -7,  45,  70,  88,
          1,   0,   0,   1,   0,   0,   0],
       [ -3,  95, -57, -18, -33, 100, -18,  85,  84, -17,  42,  29, -52,
         74,   0,   0,   0,   1,   0,   0],
       [ 47,  24, -19,  89, -74,  77,  13,  60,  83,  66, -17, -

In [246]:
c_fase_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [247]:
indices_basicas

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [248]:
indices_no_basicas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [249]:
basica=indices_no_basicas[int(q_int)]
no_basica=indices_basicas[int(p)]
indices_basicas[int(p)]=basica
indices_no_basicas[int(q_int)]=no_basica

In [296]:
indices_no_basicas

array([ 0, 22,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [250]:

indices_no_basicas_sort=np.sort(indices_no_basicas)
indices_no_basicas_sort

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 22])

In [251]:
indices_basicas

array([20, 21,  1, 23, 24, 25, 26, 27, 28, 29])

In [252]:
cn = c_fase_1[indices_no_basicas_sort]
cb = c_fase_1[indices_basicas]
cn

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1.])

In [253]:
cb

array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [254]:
r[q]

array([-246.])

In [255]:
z
z_float=float(z)

In [256]:
z_float

3503.0

In [257]:
Xb

array([  64.,  537.,   55.,  292., 1017.,    6.,  441.,  312.,  381.,
        398.])

In [258]:
Xb_actual

array([116.10526316, 592.        ,   1.44736842, 239.89473684,
       882.39473684,  45.07894737, 414.94736842, 174.5       ,
       346.26315789, 335.76315789])

In [259]:
cb

array([1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [260]:
theta_num

1.4473684210526316

In [261]:
z_float

3503.0

In [278]:
z_actual_actualizacion=z_float+r[q_int]*theta_num

In [263]:

col_An = q_int  
col_B = int(p)  
col_An

1

In [264]:
col_B

2

In [266]:
p

2

In [267]:
q

array([1])

In [268]:

# seha e poner p i q en col a i col b


An[:, col_An], B[:, col_B] = B[:, col_B].copy().reshape(-1), An[:, col_An].copy().reshape(-1)

print("Matrix An after swap:\n", An)
print("\nMatrix B after swap:\n", B)


Matrix An after swap:
 [[ 15   0  30 -54  39 -92  54 -76  75  30  54 -36 -18  79   0   0   0   0
    0   0]
 [-41   0  90  74  56  37  32  92  32  35  57  64  98 -51   0   0   0   0
    0   0]
 [-48   1 -18  20  89  15  56 -64 -78  35  65  55 -87 -23   0   0   0   0
    0   0]
 [-65   0  77  49  74  68  56 -91  37  78   9  63 -36 -63   0   0   0   0
    0   0]
 [100   0  50  86  50  81  67  52  52  87  61  72  68  97   1   0   0   0
    0   0]
 [-23   0 -69  40 -93  48 -11 -51  64 -82   0  47  65  97   0   1   0   0
    0   0]
 [ 90   0  51 -78   2  98 -11  74  -1  -7  45  70  88   1   0   0   1   0
    0   0]
 [ -3   0 -57 -18 -33 100 -18  85  84 -17  42  29 -52  74   0   0   0   1
    0   0]
 [ 47   0 -19  89 -74  77  13  60  83  66 -17 -24  -3  58   0   0   0   0
    1   0]
 [-75   0  46  72  21 -99  97  92  82 -25  41  50  -5  57   0   0   0   0
    0   1]]

Matrix B after swap:
 [[  1   0 -36   0   0   0   0   0   0   0]
 [  0   1 -38   0   0   0   0   0   0   0]
 [  0   0  38   0

In [269]:
An

array([[ 15,   0,  30, -54,  39, -92,  54, -76,  75,  30,  54, -36, -18,
         79,   0,   0,   0,   0,   0,   0],
       [-41,   0,  90,  74,  56,  37,  32,  92,  32,  35,  57,  64,  98,
        -51,   0,   0,   0,   0,   0,   0],
       [-48,   1, -18,  20,  89,  15,  56, -64, -78,  35,  65,  55, -87,
        -23,   0,   0,   0,   0,   0,   0],
       [-65,   0,  77,  49,  74,  68,  56, -91,  37,  78,   9,  63, -36,
        -63,   0,   0,   0,   0,   0,   0],
       [100,   0,  50,  86,  50,  81,  67,  52,  52,  87,  61,  72,  68,
         97,   1,   0,   0,   0,   0,   0],
       [-23,   0, -69,  40, -93,  48, -11, -51,  64, -82,   0,  47,  65,
         97,   0,   1,   0,   0,   0,   0],
       [ 90,   0,  51, -78,   2,  98, -11,  74,  -1,  -7,  45,  70,  88,
          1,   0,   0,   1,   0,   0,   0],
       [ -3,   0, -57, -18, -33, 100, -18,  85,  84, -17,  42,  29, -52,
         74,   0,   0,   0,   1,   0,   0],
       [ 47,   0, -19,  89, -74,  77,  13,  60,  83,  66, -17, -

In [270]:
b

array([  64,  537,   55,  292, 1017,    6,  441,  312,  381,  398])

In [271]:
B

array([[  1,   0, -36,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1, -38,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  38,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  36,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,  93,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0, -27,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,  18,   0,   0,   0,   1,   0,   0,   0],
       [  0,   0,  95,   0,   0,   0,   0,   1,   0,   0],
       [  0,   0,  24,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,  43,   0,   0,   0,   0,   0,   0,   1]])

In [ ]:
B_inv_2=inv(B)

Xb_actual_2=np.matmul(B_inv_2,b)
Xb_actual_2 

array([116.10526316, 592.        ,   1.44736842, 239.89473684,
       882.39473684,  45.07894737, 414.94736842, 174.5       ,
       346.26315789, 335.76315789])

In [290]:
Xb_actual

array([116.10526316, 592.        ,   1.44736842, 239.89473684,
       882.39473684,  45.07894737, 414.94736842, 174.5       ,
       346.26315789, 335.76315789])

In [ ]:
#check if xb_actual and xb_actual2 es igual

False

In [276]:
z_actual=np.dot(cb,Xb_actual_2)
z_actual

np.float64(3146.947368421052)

In [283]:
z_actual_actualizacion

np.float64(3146.9473684210525)

In [ ]:
#check if z_actual== z_actual_actualizacion

In [ ]:
#check if z > z_actual_actualizacion
z_float>float(z_actual_actualizacion)

True

In [294]:
float(z_actual_actualizacion)

3146.9473684210525

In [285]:
indices_no_basicas_sort

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 22])

In [284]:
An

array([[ 15,   0,  30, -54,  39, -92,  54, -76,  75,  30,  54, -36, -18,
         79,   0,   0,   0,   0,   0,   0],
       [-41,   0,  90,  74,  56,  37,  32,  92,  32,  35,  57,  64,  98,
        -51,   0,   0,   0,   0,   0,   0],
       [-48,   1, -18,  20,  89,  15,  56, -64, -78,  35,  65,  55, -87,
        -23,   0,   0,   0,   0,   0,   0],
       [-65,   0,  77,  49,  74,  68,  56, -91,  37,  78,   9,  63, -36,
        -63,   0,   0,   0,   0,   0,   0],
       [100,   0,  50,  86,  50,  81,  67,  52,  52,  87,  61,  72,  68,
         97,   1,   0,   0,   0,   0,   0],
       [-23,   0, -69,  40, -93,  48, -11, -51,  64, -82,   0,  47,  65,
         97,   0,   1,   0,   0,   0,   0],
       [ 90,   0,  51, -78,   2,  98, -11,  74,  -1,  -7,  45,  70,  88,
          1,   0,   0,   1,   0,   0,   0],
       [ -3,   0, -57, -18, -33, 100, -18,  85,  84, -17,  42,  29, -52,
         74,   0,   0,   0,   1,   0,   0],
       [ 47,   0, -19,  89, -74,  77,  13,  60,  83,  66, -17, -

In [298]:
# Sort the indices and get the sorted order
sorted_indices = np.argsort(indices_no_basicas)  # Get sorted index positions
sorted_indices_array = indices_no_basicas[sorted_indices]  # Sorted index array
sorted_An = An[:, sorted_indices]  # Reorder columns of An based on sorted indices

# Print results
print("Sorted Indices:", sorted_indices_array)
print("Sorted Matrix An:")
print(sorted_An)


Sorted Indices: [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 22]
Sorted Matrix An:
[[ 15  30 -54  39 -92  54 -76  75  30  54 -36 -18  79   0   0   0   0   0
    0   0]
 [-41  90  74  56  37  32  92  32  35  57  64  98 -51   0   0   0   0   0
    0   0]
 [-48 -18  20  89  15  56 -64 -78  35  65  55 -87 -23   0   0   0   0   0
    0   1]
 [-65  77  49  74  68  56 -91  37  78   9  63 -36 -63   0   0   0   0   0
    0   0]
 [100  50  86  50  81  67  52  52  87  61  72  68  97   1   0   0   0   0
    0   0]
 [-23 -69  40 -93  48 -11 -51  64 -82   0  47  65  97   0   1   0   0   0
    0   0]
 [ 90  51 -78   2  98 -11  74  -1  -7  45  70  88   1   0   0   1   0   0
    0   0]
 [ -3 -57 -18 -33 100 -18  85  84 -17  42  29 -52  74   0   0   0   1   0
    0   0]
 [ 47 -19  89 -74  77  13  60  83  66 -17 -24  -3  58   0   0   0   0   1
    0   0]
 [-75  46  72  21 -99  97  92  82 -25  41  50  -5  57   0   0   0   0   0
    1   0]]


In [303]:
print('An')
print(sorted_An)
print('B')
print(B)
print('cn')
print(cn)
print('cb')
print(cb)
print('Xb')
print(Xb_actual_2)
print('z')
print(z_actual_actualizacion)
print('theta')
print(theta_num)
print('B(p)')
print(col_B)


An
[[ 15  30 -54  39 -92  54 -76  75  30  54 -36 -18  79   0   0   0   0   0
    0   0]
 [-41  90  74  56  37  32  92  32  35  57  64  98 -51   0   0   0   0   0
    0   0]
 [-48 -18  20  89  15  56 -64 -78  35  65  55 -87 -23   0   0   0   0   0
    0   1]
 [-65  77  49  74  68  56 -91  37  78   9  63 -36 -63   0   0   0   0   0
    0   0]
 [100  50  86  50  81  67  52  52  87  61  72  68  97   1   0   0   0   0
    0   0]
 [-23 -69  40 -93  48 -11 -51  64 -82   0  47  65  97   0   1   0   0   0
    0   0]
 [ 90  51 -78   2  98 -11  74  -1  -7  45  70  88   1   0   0   1   0   0
    0   0]
 [ -3 -57 -18 -33 100 -18  85  84 -17  42  29 -52  74   0   0   0   1   0
    0   0]
 [ 47 -19  89 -74  77  13  60  83  66 -17 -24  -3  58   0   0   0   0   1
    0   0]
 [-75  46  72  21 -99  97  92  82 -25  41  50  -5  57   0   0   0   0   0
    1   0]]
B
[[  1   0 -36   0   0   0   0   0   0   0]
 [  0   1 -38   0   0   0   0   0   0   0]
 [  0   0  38   0   0   0   0   0   0   0]
 [  0   0  36  